// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvjbwwkjcibthjnogmaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2amJ3d2tqY2lidGhqbm9nbWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzU1MjgsImV4cCI6MjA2NzA1MTUyOH0.NagxL6SP5CsYIc1M5BlHp14UiilI7UwGabGVMa6j1e8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});